#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-contourpy
Version  : 1.0.6
Release  : 6
URL      : https://files.pythonhosted.org/packages/8f/4f/8a5789867f2a928fd9b32e7e8d4bc0f27a765aa7056989e7427f2c2a1966/contourpy-1.0.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/8f/4f/8a5789867f2a928fd9b32e7e8d4bc0f27a765aa7056989e7427f2c2a1966/contourpy-1.0.6.tar.gz
Summary  : Python library for calculating contours of 2D quadrilateral grids
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-contourpy-filemap = %{version}-%{release}
Requires: pypi-contourpy-lib = %{version}-%{release}
Requires: pypi-contourpy-license = %{version}-%{release}
Requires: pypi-contourpy-python = %{version}-%{release}
Requires: pypi-contourpy-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(numpy)
BuildRequires : pypi(pybind11)
BuildRequires : pypi(setuptools)

%description
<img alt="ContourPy" src="https://raw.githubusercontent.com/contourpy/contourpy/main/docs/_static/contourpy_logo_horiz.svg" height="90">

%package filemap
Summary: filemap components for the pypi-contourpy package.
Group: Default

%description filemap
filemap components for the pypi-contourpy package.


%package lib
Summary: lib components for the pypi-contourpy package.
Group: Libraries
Requires: pypi-contourpy-license = %{version}-%{release}
Requires: pypi-contourpy-filemap = %{version}-%{release}

%description lib
lib components for the pypi-contourpy package.


%package license
Summary: license components for the pypi-contourpy package.
Group: Default

%description license
license components for the pypi-contourpy package.


%package python
Summary: python components for the pypi-contourpy package.
Group: Default
Requires: pypi-contourpy-python3 = %{version}-%{release}

%description python
python components for the pypi-contourpy package.


%package python3
Summary: python3 components for the pypi-contourpy package.
Group: Default
Requires: pypi-contourpy-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(contourpy)
Requires: pypi(numpy)

%description python3
python3 components for the pypi-contourpy package.


%prep
%setup -q -n contourpy-1.0.6
cd %{_builddir}/contourpy-1.0.6
pushd ..
cp -a contourpy-1.0.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667226722
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-contourpy
cp %{_builddir}/contourpy-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-contourpy/0317372d3b845cebe6fc42326867cb77386204e6 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-contourpy

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-contourpy/0317372d3b845cebe6fc42326867cb77386204e6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
